### ISSUE TITLE
help in installing

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/storage-costs-evaluator#13]
Hello again.
I was trying to install this, but no luck. I am totally ignorant of haskell & npm, so... I need help. 
After doing
stack build
apt install webpack
it gets stuck on npm run-script build with 

Thanks!
[2021-02-22T11_34_41_580Z-debug.log](https://github.com/ds-wizard/storage-costs-evaluator/files/6021732/2021-02-22T11_34_41_580Z-debug.log)

**Comment by MarekSuchanek** [comment]
Hi, seems like there was some issue with `package.json`... fixed in https://github.com/ds-wizard/storage-costs-evaluator/commit/8c7705994c9be761e1f069f32aea9154b8ab2173. But I also added to the README file how to run this using Docker (so you don't have to build Haskell and run npm/webpack at all).

**Comment by froggypaule** [comment]
hopla! this works. Many thanks.
